# Require the necessary scripts for React Native and permissions setup
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Require React Native's pod setup and permissions setup
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Set the platform version for iOS
platform :ios, '17.0'
prepare_react_native_project!

# Uncomment wanted permissions for your project
setup_permissions([
  # 'Bluetooth',
  'Camera',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'MediaLibrary',
  # 'Notifications',
  'PhotoLibrary',
])

# If using frameworks (can be set to static or dynamic), but for now this is commented out.
# use_frameworks! :linkage => :static

# Add pre_install hook for RNMapboxMaps
pre_install do |installer|
  $RNMapboxMaps.pre_install(installer)
end

use_frameworks! :linkage => :static


# Define the main target for your app
target 'app' do
  # Set up native modules from React Native
  config = use_native_modules!
  
  # React Native configuration
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,   # Hermes can be enabled/disabled here
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  # Add post_install hook for RNMapboxMaps
  post_install do |installer|
    # Call the post_install method for RNMapboxMaps
    $RNMapboxMaps.post_install(installer)

    # Post-install configuration for React Native
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

$RNMapboxMapsVersion = '= 11.0.0'